import { describe, it, expect } from 'vitest';
import PDFDocument from 'pdfkit';
import appConfig from '../src/config/appConfig.js';

describe('Report App Name Centralization Tests', () => {
  it('has appConfig with appName configured as FOTLAB', () => {
    expect(appConfig).toBeDefined();
    expect(appConfig.appName).toBe('FOTLAB');
  });

  it('uses appConfig.appName in report text generation', async () => {
    const doc = new PDFDocument({ margin: 30, size: 'A4', compress: false });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));

    const pdfBufferPromise = new Promise((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
    });

    // Emulate report header generation
    doc.text(appConfig.appName, 50, 50);
    doc.text(`${appConfig.appName}  ·  Full Inventory Status Report`, 50, 70);
    doc.text(`Generated by ${appConfig.appName}`, 50, 90);
    doc.end();

    const pdfBuffer = await pdfBufferPromise;
    const pdfRaw = pdfBuffer.toString('latin1');

    // PDFKit writes text in hex chunks in TJ operator (e.g. 544c4142 = TLAB)
    const fotlabHex = Buffer.from('TLAB').toString('hex');
    const fotcmsHex = Buffer.from('CMS').toString('hex');

    expect(pdfRaw.toLowerCase()).toContain(fotlabHex.toLowerCase());
    expect(pdfRaw.toLowerCase()).not.toContain(fotcmsHex.toLowerCase());
  });
});

